require("phillip.plugins-setup")
require("phillip.core.options")
require("phillip.core.keymaps")
require("phillip.core.colorscheme")
require("phillip.plugins.comment")
require("phillip.plugins.nvim-tree")
require("phillip.plugins.lualine")
require("phillip.plugins.telescope")
require("phillip.plugins.nvim-cmp")
require("phillip.plugins.lsp.mason")
require("phillip.plugins.lsp.lspsaga")
require("phillip.plugins.lsp.lspconfig")

